/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as CartRouteImport } from './routes/cart'
import { Route as BoutiquesRouteImport } from './routes/boutiques'
import { Route as BoutiqueManifestDotwebmanifestRouteImport } from './routes/boutique-manifest[.]webmanifest'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AideRouteImport } from './routes/aide'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BoutiqueRouteRouteImport } from './routes/boutique/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BoutiqueIndexRouteImport } from './routes/boutique/index'
import { Route as VendorSlugRouteImport } from './routes/vendor.$slug'
import { Route as ProductProductIdRouteImport } from './routes/product.$productId'
import { Route as OrderProductIdRouteImport } from './routes/order.$productId'
import { Route as BoutiqueProduitRouteImport } from './routes/boutique/produit'
import { Route as BoutiquePanierRouteImport } from './routes/boutique/panier'
import { Route as BoutiqueConnexionRouteImport } from './routes/boutique/connexion'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedParrainageRouteImport } from './routes/_authenticated/parrainage'
import { Route as AuthenticatedOrdersRouteImport } from './routes/_authenticated/orders'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as BoutiqueAdminRouteRouteImport } from './routes/boutique/admin/route'
import { Route as BoutiqueAdminRapportsRouteImport } from './routes/boutique/admin/rapports'
import { Route as BoutiqueAdminPromoRouteImport } from './routes/boutique/admin/promo'
import { Route as BoutiqueAdminProduitsRouteImport } from './routes/boutique/admin/produits'
import { Route as BoutiqueAdminPosRouteImport } from './routes/boutique/admin/pos'
import { Route as BoutiqueAdminParametresRouteImport } from './routes/boutique/admin/parametres'
import { Route as BoutiqueAdminFournisseursRouteImport } from './routes/boutique/admin/fournisseurs'
import { Route as BoutiqueAdminFacturesRouteImport } from './routes/boutique/admin/factures'
import { Route as BoutiqueAdminEquipeRouteImport } from './routes/boutique/admin/equipe'
import { Route as BoutiqueAdminCreditsRouteImport } from './routes/boutique/admin/credits'
import { Route as BoutiqueAdminCommandesRouteImport } from './routes/boutique/admin/commandes'
import { Route as BoutiqueAdminCategoriesRouteImport } from './routes/boutique/admin/categories'
import { Route as AuthenticatedOrdersOrderIdRouteImport } from './routes/_authenticated/orders.$orderId'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const BoutiquesRoute = BoutiquesRouteImport.update({
  id: '/boutiques',
  path: '/boutiques',
  getParentRoute: () => rootRouteImport,
} as any)
const BoutiqueManifestDotwebmanifestRoute =
  BoutiqueManifestDotwebmanifestRouteImport.update({
    id: '/boutique-manifest.webmanifest',
    path: '/boutique-manifest.webmanifest',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AideRoute = AideRouteImport.update({
  id: '/aide',
  path: '/aide',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BoutiqueRouteRoute = BoutiqueRouteRouteImport.update({
  id: '/boutique',
  path: '/boutique',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BoutiqueIndexRoute = BoutiqueIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BoutiqueRouteRoute,
} as any)
const VendorSlugRoute = VendorSlugRouteImport.update({
  id: '/vendor/$slug',
  path: '/vendor/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductProductIdRoute = ProductProductIdRouteImport.update({
  id: '/product/$productId',
  path: '/product/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderProductIdRoute = OrderProductIdRouteImport.update({
  id: '/order/$productId',
  path: '/order/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const BoutiqueProduitRoute = BoutiqueProduitRouteImport.update({
  id: '/produit',
  path: '/produit',
  getParentRoute: () => BoutiqueRouteRoute,
} as any)
const BoutiquePanierRoute = BoutiquePanierRouteImport.update({
  id: '/panier',
  path: '/panier',
  getParentRoute: () => BoutiqueRouteRoute,
} as any)
const BoutiqueConnexionRoute = BoutiqueConnexionRouteImport.update({
  id: '/connexion',
  path: '/connexion',
  getParentRoute: () => BoutiqueRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedParrainageRoute = AuthenticatedParrainageRouteImport.update({
  id: '/parrainage',
  path: '/parrainage',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrdersRoute = AuthenticatedOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const BoutiqueAdminRouteRoute = BoutiqueAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => BoutiqueRouteRoute,
} as any)
const BoutiqueAdminRapportsRoute = BoutiqueAdminRapportsRouteImport.update({
  id: '/rapports',
  path: '/rapports',
  getParentRoute: () => BoutiqueAdminRouteRoute,
} as any)
const BoutiqueAdminPromoRoute = BoutiqueAdminPromoRouteImport.update({
  id: '/promo',
  path: '/promo',
  getParentRoute: () => BoutiqueAdminRouteRoute,
} as any)
const BoutiqueAdminProduitsRoute = BoutiqueAdminProduitsRouteImport.update({
  id: '/produits',
  path: '/produits',
  getParentRoute: () => BoutiqueAdminRouteRoute,
} as any)
const BoutiqueAdminPosRoute = BoutiqueAdminPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => BoutiqueAdminRouteRoute,
} as any)
const BoutiqueAdminParametresRoute = BoutiqueAdminParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => BoutiqueAdminRouteRoute,
} as any)
const BoutiqueAdminFournisseursRoute =
  BoutiqueAdminFournisseursRouteImport.update({
    id: '/fournisseurs',
    path: '/fournisseurs',
    getParentRoute: () => BoutiqueAdminRouteRoute,
  } as any)
const BoutiqueAdminFacturesRoute = BoutiqueAdminFacturesRouteImport.update({
  id: '/factures',
  path: '/factures',
  getParentRoute: () => BoutiqueAdminRouteRoute,
} as any)
const BoutiqueAdminEquipeRoute = BoutiqueAdminEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => BoutiqueAdminRouteRoute,
} as any)
const BoutiqueAdminCreditsRoute = BoutiqueAdminCreditsRouteImport.update({
  id: '/credits',
  path: '/credits',
  getParentRoute: () => BoutiqueAdminRouteRoute,
} as any)
const BoutiqueAdminCommandesRoute = BoutiqueAdminCommandesRouteImport.update({
  id: '/commandes',
  path: '/commandes',
  getParentRoute: () => BoutiqueAdminRouteRoute,
} as any)
const BoutiqueAdminCategoriesRoute = BoutiqueAdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => BoutiqueAdminRouteRoute,
} as any)
const AuthenticatedOrdersOrderIdRoute =
  AuthenticatedOrdersOrderIdRouteImport.update({
    id: '/$orderId',
    path: '/$orderId',
    getParentRoute: () => AuthenticatedOrdersRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/boutique': typeof BoutiqueRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/aide': typeof AideRoute
  '/auth': typeof AuthRoute
  '/boutique-manifest.webmanifest': typeof BoutiqueManifestDotwebmanifestRoute
  '/boutiques': typeof BoutiquesRoute
  '/cart': typeof CartRoute
  '/catalog': typeof CatalogRoute
  '/contact': typeof ContactRoute
  '/favorites': typeof FavoritesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/boutique/admin': typeof BoutiqueAdminRouteRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/orders': typeof AuthenticatedOrdersRouteWithChildren
  '/parrainage': typeof AuthenticatedParrainageRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/boutique/connexion': typeof BoutiqueConnexionRoute
  '/boutique/panier': typeof BoutiquePanierRoute
  '/boutique/produit': typeof BoutiqueProduitRoute
  '/order/$productId': typeof OrderProductIdRoute
  '/product/$productId': typeof ProductProductIdRoute
  '/vendor/$slug': typeof VendorSlugRoute
  '/boutique/': typeof BoutiqueIndexRoute
  '/orders/$orderId': typeof AuthenticatedOrdersOrderIdRoute
  '/boutique/admin/categories': typeof BoutiqueAdminCategoriesRoute
  '/boutique/admin/commandes': typeof BoutiqueAdminCommandesRoute
  '/boutique/admin/credits': typeof BoutiqueAdminCreditsRoute
  '/boutique/admin/equipe': typeof BoutiqueAdminEquipeRoute
  '/boutique/admin/factures': typeof BoutiqueAdminFacturesRoute
  '/boutique/admin/fournisseurs': typeof BoutiqueAdminFournisseursRoute
  '/boutique/admin/parametres': typeof BoutiqueAdminParametresRoute
  '/boutique/admin/pos': typeof BoutiqueAdminPosRoute
  '/boutique/admin/produits': typeof BoutiqueAdminProduitsRoute
  '/boutique/admin/promo': typeof BoutiqueAdminPromoRoute
  '/boutique/admin/rapports': typeof BoutiqueAdminRapportsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/aide': typeof AideRoute
  '/auth': typeof AuthRoute
  '/boutique-manifest.webmanifest': typeof BoutiqueManifestDotwebmanifestRoute
  '/boutiques': typeof BoutiquesRoute
  '/cart': typeof CartRoute
  '/catalog': typeof CatalogRoute
  '/contact': typeof ContactRoute
  '/favorites': typeof FavoritesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/boutique/admin': typeof BoutiqueAdminRouteRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/orders': typeof AuthenticatedOrdersRouteWithChildren
  '/parrainage': typeof AuthenticatedParrainageRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/boutique/connexion': typeof BoutiqueConnexionRoute
  '/boutique/panier': typeof BoutiquePanierRoute
  '/boutique/produit': typeof BoutiqueProduitRoute
  '/order/$productId': typeof OrderProductIdRoute
  '/product/$productId': typeof ProductProductIdRoute
  '/vendor/$slug': typeof VendorSlugRoute
  '/boutique': typeof BoutiqueIndexRoute
  '/orders/$orderId': typeof AuthenticatedOrdersOrderIdRoute
  '/boutique/admin/categories': typeof BoutiqueAdminCategoriesRoute
  '/boutique/admin/commandes': typeof BoutiqueAdminCommandesRoute
  '/boutique/admin/credits': typeof BoutiqueAdminCreditsRoute
  '/boutique/admin/equipe': typeof BoutiqueAdminEquipeRoute
  '/boutique/admin/factures': typeof BoutiqueAdminFacturesRoute
  '/boutique/admin/fournisseurs': typeof BoutiqueAdminFournisseursRoute
  '/boutique/admin/parametres': typeof BoutiqueAdminParametresRoute
  '/boutique/admin/pos': typeof BoutiqueAdminPosRoute
  '/boutique/admin/produits': typeof BoutiqueAdminProduitsRoute
  '/boutique/admin/promo': typeof BoutiqueAdminPromoRoute
  '/boutique/admin/rapports': typeof BoutiqueAdminRapportsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/boutique': typeof BoutiqueRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/aide': typeof AideRoute
  '/auth': typeof AuthRoute
  '/boutique-manifest.webmanifest': typeof BoutiqueManifestDotwebmanifestRoute
  '/boutiques': typeof BoutiquesRoute
  '/cart': typeof CartRoute
  '/catalog': typeof CatalogRoute
  '/contact': typeof ContactRoute
  '/favorites': typeof FavoritesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/boutique/admin': typeof BoutiqueAdminRouteRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/orders': typeof AuthenticatedOrdersRouteWithChildren
  '/_authenticated/parrainage': typeof AuthenticatedParrainageRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/boutique/connexion': typeof BoutiqueConnexionRoute
  '/boutique/panier': typeof BoutiquePanierRoute
  '/boutique/produit': typeof BoutiqueProduitRoute
  '/order/$productId': typeof OrderProductIdRoute
  '/product/$productId': typeof ProductProductIdRoute
  '/vendor/$slug': typeof VendorSlugRoute
  '/boutique/': typeof BoutiqueIndexRoute
  '/_authenticated/orders/$orderId': typeof AuthenticatedOrdersOrderIdRoute
  '/boutique/admin/categories': typeof BoutiqueAdminCategoriesRoute
  '/boutique/admin/commandes': typeof BoutiqueAdminCommandesRoute
  '/boutique/admin/credits': typeof BoutiqueAdminCreditsRoute
  '/boutique/admin/equipe': typeof BoutiqueAdminEquipeRoute
  '/boutique/admin/factures': typeof BoutiqueAdminFacturesRoute
  '/boutique/admin/fournisseurs': typeof BoutiqueAdminFournisseursRoute
  '/boutique/admin/parametres': typeof BoutiqueAdminParametresRoute
  '/boutique/admin/pos': typeof BoutiqueAdminPosRoute
  '/boutique/admin/produits': typeof BoutiqueAdminProduitsRoute
  '/boutique/admin/promo': typeof BoutiqueAdminPromoRoute
  '/boutique/admin/rapports': typeof BoutiqueAdminRapportsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/boutique'
    | '/about'
    | '/aide'
    | '/auth'
    | '/boutique-manifest.webmanifest'
    | '/boutiques'
    | '/cart'
    | '/catalog'
    | '/contact'
    | '/favorites'
    | '/reset-password'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/terms'
    | '/boutique/admin'
    | '/dashboard'
    | '/orders'
    | '/parrainage'
    | '/profile'
    | '/boutique/connexion'
    | '/boutique/panier'
    | '/boutique/produit'
    | '/order/$productId'
    | '/product/$productId'
    | '/vendor/$slug'
    | '/boutique/'
    | '/orders/$orderId'
    | '/boutique/admin/categories'
    | '/boutique/admin/commandes'
    | '/boutique/admin/credits'
    | '/boutique/admin/equipe'
    | '/boutique/admin/factures'
    | '/boutique/admin/fournisseurs'
    | '/boutique/admin/parametres'
    | '/boutique/admin/pos'
    | '/boutique/admin/produits'
    | '/boutique/admin/promo'
    | '/boutique/admin/rapports'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/aide'
    | '/auth'
    | '/boutique-manifest.webmanifest'
    | '/boutiques'
    | '/cart'
    | '/catalog'
    | '/contact'
    | '/favorites'
    | '/reset-password'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/terms'
    | '/boutique/admin'
    | '/dashboard'
    | '/orders'
    | '/parrainage'
    | '/profile'
    | '/boutique/connexion'
    | '/boutique/panier'
    | '/boutique/produit'
    | '/order/$productId'
    | '/product/$productId'
    | '/vendor/$slug'
    | '/boutique'
    | '/orders/$orderId'
    | '/boutique/admin/categories'
    | '/boutique/admin/commandes'
    | '/boutique/admin/credits'
    | '/boutique/admin/equipe'
    | '/boutique/admin/factures'
    | '/boutique/admin/fournisseurs'
    | '/boutique/admin/parametres'
    | '/boutique/admin/pos'
    | '/boutique/admin/produits'
    | '/boutique/admin/promo'
    | '/boutique/admin/rapports'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/boutique'
    | '/about'
    | '/aide'
    | '/auth'
    | '/boutique-manifest.webmanifest'
    | '/boutiques'
    | '/cart'
    | '/catalog'
    | '/contact'
    | '/favorites'
    | '/reset-password'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/terms'
    | '/boutique/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/orders'
    | '/_authenticated/parrainage'
    | '/_authenticated/profile'
    | '/boutique/connexion'
    | '/boutique/panier'
    | '/boutique/produit'
    | '/order/$productId'
    | '/product/$productId'
    | '/vendor/$slug'
    | '/boutique/'
    | '/_authenticated/orders/$orderId'
    | '/boutique/admin/categories'
    | '/boutique/admin/commandes'
    | '/boutique/admin/credits'
    | '/boutique/admin/equipe'
    | '/boutique/admin/factures'
    | '/boutique/admin/fournisseurs'
    | '/boutique/admin/parametres'
    | '/boutique/admin/pos'
    | '/boutique/admin/produits'
    | '/boutique/admin/promo'
    | '/boutique/admin/rapports'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  BoutiqueRouteRoute: typeof BoutiqueRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AideRoute: typeof AideRoute
  AuthRoute: typeof AuthRoute
  BoutiqueManifestDotwebmanifestRoute: typeof BoutiqueManifestDotwebmanifestRoute
  BoutiquesRoute: typeof BoutiquesRoute
  CartRoute: typeof CartRoute
  CatalogRoute: typeof CatalogRoute
  ContactRoute: typeof ContactRoute
  FavoritesRoute: typeof FavoritesRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  OrderProductIdRoute: typeof OrderProductIdRoute
  ProductProductIdRoute: typeof ProductProductIdRoute
  VendorSlugRoute: typeof VendorSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boutiques': {
      id: '/boutiques'
      path: '/boutiques'
      fullPath: '/boutiques'
      preLoaderRoute: typeof BoutiquesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boutique-manifest.webmanifest': {
      id: '/boutique-manifest.webmanifest'
      path: '/boutique-manifest.webmanifest'
      fullPath: '/boutique-manifest.webmanifest'
      preLoaderRoute: typeof BoutiqueManifestDotwebmanifestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aide': {
      id: '/aide'
      path: '/aide'
      fullPath: '/aide'
      preLoaderRoute: typeof AideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boutique': {
      id: '/boutique'
      path: '/boutique'
      fullPath: '/boutique'
      preLoaderRoute: typeof BoutiqueRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boutique/': {
      id: '/boutique/'
      path: '/'
      fullPath: '/boutique/'
      preLoaderRoute: typeof BoutiqueIndexRouteImport
      parentRoute: typeof BoutiqueRouteRoute
    }
    '/vendor/$slug': {
      id: '/vendor/$slug'
      path: '/vendor/$slug'
      fullPath: '/vendor/$slug'
      preLoaderRoute: typeof VendorSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$productId': {
      id: '/product/$productId'
      path: '/product/$productId'
      fullPath: '/product/$productId'
      preLoaderRoute: typeof ProductProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/$productId': {
      id: '/order/$productId'
      path: '/order/$productId'
      fullPath: '/order/$productId'
      preLoaderRoute: typeof OrderProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boutique/produit': {
      id: '/boutique/produit'
      path: '/produit'
      fullPath: '/boutique/produit'
      preLoaderRoute: typeof BoutiqueProduitRouteImport
      parentRoute: typeof BoutiqueRouteRoute
    }
    '/boutique/panier': {
      id: '/boutique/panier'
      path: '/panier'
      fullPath: '/boutique/panier'
      preLoaderRoute: typeof BoutiquePanierRouteImport
      parentRoute: typeof BoutiqueRouteRoute
    }
    '/boutique/connexion': {
      id: '/boutique/connexion'
      path: '/connexion'
      fullPath: '/boutique/connexion'
      preLoaderRoute: typeof BoutiqueConnexionRouteImport
      parentRoute: typeof BoutiqueRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/parrainage': {
      id: '/_authenticated/parrainage'
      path: '/parrainage'
      fullPath: '/parrainage'
      preLoaderRoute: typeof AuthenticatedParrainageRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orders': {
      id: '/_authenticated/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthenticatedOrdersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/boutique/admin': {
      id: '/boutique/admin'
      path: '/admin'
      fullPath: '/boutique/admin'
      preLoaderRoute: typeof BoutiqueAdminRouteRouteImport
      parentRoute: typeof BoutiqueRouteRoute
    }
    '/boutique/admin/rapports': {
      id: '/boutique/admin/rapports'
      path: '/rapports'
      fullPath: '/boutique/admin/rapports'
      preLoaderRoute: typeof BoutiqueAdminRapportsRouteImport
      parentRoute: typeof BoutiqueAdminRouteRoute
    }
    '/boutique/admin/promo': {
      id: '/boutique/admin/promo'
      path: '/promo'
      fullPath: '/boutique/admin/promo'
      preLoaderRoute: typeof BoutiqueAdminPromoRouteImport
      parentRoute: typeof BoutiqueAdminRouteRoute
    }
    '/boutique/admin/produits': {
      id: '/boutique/admin/produits'
      path: '/produits'
      fullPath: '/boutique/admin/produits'
      preLoaderRoute: typeof BoutiqueAdminProduitsRouteImport
      parentRoute: typeof BoutiqueAdminRouteRoute
    }
    '/boutique/admin/pos': {
      id: '/boutique/admin/pos'
      path: '/pos'
      fullPath: '/boutique/admin/pos'
      preLoaderRoute: typeof BoutiqueAdminPosRouteImport
      parentRoute: typeof BoutiqueAdminRouteRoute
    }
    '/boutique/admin/parametres': {
      id: '/boutique/admin/parametres'
      path: '/parametres'
      fullPath: '/boutique/admin/parametres'
      preLoaderRoute: typeof BoutiqueAdminParametresRouteImport
      parentRoute: typeof BoutiqueAdminRouteRoute
    }
    '/boutique/admin/fournisseurs': {
      id: '/boutique/admin/fournisseurs'
      path: '/fournisseurs'
      fullPath: '/boutique/admin/fournisseurs'
      preLoaderRoute: typeof BoutiqueAdminFournisseursRouteImport
      parentRoute: typeof BoutiqueAdminRouteRoute
    }
    '/boutique/admin/factures': {
      id: '/boutique/admin/factures'
      path: '/factures'
      fullPath: '/boutique/admin/factures'
      preLoaderRoute: typeof BoutiqueAdminFacturesRouteImport
      parentRoute: typeof BoutiqueAdminRouteRoute
    }
    '/boutique/admin/equipe': {
      id: '/boutique/admin/equipe'
      path: '/equipe'
      fullPath: '/boutique/admin/equipe'
      preLoaderRoute: typeof BoutiqueAdminEquipeRouteImport
      parentRoute: typeof BoutiqueAdminRouteRoute
    }
    '/boutique/admin/credits': {
      id: '/boutique/admin/credits'
      path: '/credits'
      fullPath: '/boutique/admin/credits'
      preLoaderRoute: typeof BoutiqueAdminCreditsRouteImport
      parentRoute: typeof BoutiqueAdminRouteRoute
    }
    '/boutique/admin/commandes': {
      id: '/boutique/admin/commandes'
      path: '/commandes'
      fullPath: '/boutique/admin/commandes'
      preLoaderRoute: typeof BoutiqueAdminCommandesRouteImport
      parentRoute: typeof BoutiqueAdminRouteRoute
    }
    '/boutique/admin/categories': {
      id: '/boutique/admin/categories'
      path: '/categories'
      fullPath: '/boutique/admin/categories'
      preLoaderRoute: typeof BoutiqueAdminCategoriesRouteImport
      parentRoute: typeof BoutiqueAdminRouteRoute
    }
    '/_authenticated/orders/$orderId': {
      id: '/_authenticated/orders/$orderId'
      path: '/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof AuthenticatedOrdersOrderIdRouteImport
      parentRoute: typeof AuthenticatedOrdersRoute
    }
  }
}

interface AuthenticatedOrdersRouteChildren {
  AuthenticatedOrdersOrderIdRoute: typeof AuthenticatedOrdersOrderIdRoute
}

const AuthenticatedOrdersRouteChildren: AuthenticatedOrdersRouteChildren = {
  AuthenticatedOrdersOrderIdRoute: AuthenticatedOrdersOrderIdRoute,
}

const AuthenticatedOrdersRouteWithChildren =
  AuthenticatedOrdersRoute._addFileChildren(AuthenticatedOrdersRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedOrdersRoute: typeof AuthenticatedOrdersRouteWithChildren
  AuthenticatedParrainageRoute: typeof AuthenticatedParrainageRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedOrdersRoute: AuthenticatedOrdersRouteWithChildren,
  AuthenticatedParrainageRoute: AuthenticatedParrainageRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface BoutiqueAdminRouteRouteChildren {
  BoutiqueAdminCategoriesRoute: typeof BoutiqueAdminCategoriesRoute
  BoutiqueAdminCommandesRoute: typeof BoutiqueAdminCommandesRoute
  BoutiqueAdminCreditsRoute: typeof BoutiqueAdminCreditsRoute
  BoutiqueAdminEquipeRoute: typeof BoutiqueAdminEquipeRoute
  BoutiqueAdminFacturesRoute: typeof BoutiqueAdminFacturesRoute
  BoutiqueAdminFournisseursRoute: typeof BoutiqueAdminFournisseursRoute
  BoutiqueAdminParametresRoute: typeof BoutiqueAdminParametresRoute
  BoutiqueAdminPosRoute: typeof BoutiqueAdminPosRoute
  BoutiqueAdminProduitsRoute: typeof BoutiqueAdminProduitsRoute
  BoutiqueAdminPromoRoute: typeof BoutiqueAdminPromoRoute
  BoutiqueAdminRapportsRoute: typeof BoutiqueAdminRapportsRoute
}

const BoutiqueAdminRouteRouteChildren: BoutiqueAdminRouteRouteChildren = {
  BoutiqueAdminCategoriesRoute: BoutiqueAdminCategoriesRoute,
  BoutiqueAdminCommandesRoute: BoutiqueAdminCommandesRoute,
  BoutiqueAdminCreditsRoute: BoutiqueAdminCreditsRoute,
  BoutiqueAdminEquipeRoute: BoutiqueAdminEquipeRoute,
  BoutiqueAdminFacturesRoute: BoutiqueAdminFacturesRoute,
  BoutiqueAdminFournisseursRoute: BoutiqueAdminFournisseursRoute,
  BoutiqueAdminParametresRoute: BoutiqueAdminParametresRoute,
  BoutiqueAdminPosRoute: BoutiqueAdminPosRoute,
  BoutiqueAdminProduitsRoute: BoutiqueAdminProduitsRoute,
  BoutiqueAdminPromoRoute: BoutiqueAdminPromoRoute,
  BoutiqueAdminRapportsRoute: BoutiqueAdminRapportsRoute,
}

const BoutiqueAdminRouteRouteWithChildren =
  BoutiqueAdminRouteRoute._addFileChildren(BoutiqueAdminRouteRouteChildren)

interface BoutiqueRouteRouteChildren {
  BoutiqueAdminRouteRoute: typeof BoutiqueAdminRouteRouteWithChildren
  BoutiqueConnexionRoute: typeof BoutiqueConnexionRoute
  BoutiquePanierRoute: typeof BoutiquePanierRoute
  BoutiqueProduitRoute: typeof BoutiqueProduitRoute
  BoutiqueIndexRoute: typeof BoutiqueIndexRoute
}

const BoutiqueRouteRouteChildren: BoutiqueRouteRouteChildren = {
  BoutiqueAdminRouteRoute: BoutiqueAdminRouteRouteWithChildren,
  BoutiqueConnexionRoute: BoutiqueConnexionRoute,
  BoutiquePanierRoute: BoutiquePanierRoute,
  BoutiqueProduitRoute: BoutiqueProduitRoute,
  BoutiqueIndexRoute: BoutiqueIndexRoute,
}

const BoutiqueRouteRouteWithChildren = BoutiqueRouteRoute._addFileChildren(
  BoutiqueRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  BoutiqueRouteRoute: BoutiqueRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AideRoute: AideRoute,
  AuthRoute: AuthRoute,
  BoutiqueManifestDotwebmanifestRoute: BoutiqueManifestDotwebmanifestRoute,
  BoutiquesRoute: BoutiquesRoute,
  CartRoute: CartRoute,
  CatalogRoute: CatalogRoute,
  ContactRoute: ContactRoute,
  FavoritesRoute: FavoritesRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  OrderProductIdRoute: OrderProductIdRoute,
  ProductProductIdRoute: ProductProductIdRoute,
  VendorSlugRoute: VendorSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
