// This file is automatically generated. Do not edit it directly.
// Server-side Supabase client with service role key - bypasses RLS.
// Use this for admin operations in server functions and server routes only.
// For user-authenticated queries (with RLS), use the auth middleware instead.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function createSupabaseAdminClient() {
  const SUPABASE_URL = process.env.SUPABASE_URL;
  const SUPABASE_SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY;

  if (!SUPABASE_URL) {
    const message = 'Missing SUPABASE_URL environment variable.';
    console.error(`[Supabase Admin] ${message}`);
    throw new Error(message);
  }

  if (!SUPABASE_SERVICE_ROLE_KEY) {
    const message =
      'Missing SUPABASE_SERVICE_ROLE_KEY. ' +
      'Va dans Supabase Dashboard → Project Settings → API → service_role → copie la clé et ajoute-la dans .env';
    console.error(`[Supabase Admin] ${message}`);
    throw new Error(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, {
    auth: {
      storage: undefined,
      persistSession: false,
      autoRefreshToken: false,
    },
  });
}

// Initialise immédiatement au chargement du module (pas de lazy init)
// pour détecter les erreurs de config au démarrage du serveur.
function getAdminClient() {
  try {
    const client = createSupabaseAdminClient();
    console.log('[Supabase Admin] ✅ Client service_role initialisé avec succès');
    return client;
  } catch (e: any) {
    console.error('[Supabase Admin] ❌ ERREUR init:', e.message);
    throw e;
  }
}

let _supabaseAdmin: ReturnType<typeof createSupabaseAdminClient> | null = null;
let _initError: Error | null = null;

try {
  _supabaseAdmin = getAdminClient();
} catch (e: any) {
  _initError = e;
}

// Server-side Supabase client with service role - bypasses RLS
export const supabaseAdmin = new Proxy({} as ReturnType<typeof createSupabaseAdminClient>, {
  get(_, prop, receiver) {
    if (_initError) throw _initError;
    if (!_supabaseAdmin) throw new Error('supabaseAdmin not initialized');
    return Reflect.get(_supabaseAdmin, prop, receiver);
  },
});
