// This file is automatically generated. Do not edit it directly.
import { createClient, type SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

/**
 * Verrou d'auth anti-deadlock.
 *
 * INCIDENT (juin 2026) : sans config `lock`, supabase-js utilise le Web Lock par défaut
 * (`navigator.locks`). Si un onglet/contexte est gelé ou tué en plein refresh (fréquent
 * sur mobile/PWA), le verrou peut rester tenu → TOUTES les opérations d'auth suivantes
 * (`getSession`, `signInWithPassword`, refresh) attendent indéfiniment → l'utilisateur
 * est "déconnecté" et NE PEUT PLUS se reconnecter, jusqu'à ce qu'il vide les données du
 * site. Les logs serveur ne montraient que des 200 : les tentatives bloquées n'atteignent
 * jamais le serveur → blocage 100% côté client = verrou figé.
 *
 * Ce verrou conserve l'exclusion mutuelle inter-onglets dans le cas normal, mais plafonne
 * l'attente (anti-deadlock) : s'il n'obtient pas le verrou à temps, il exécute quand même.
 *
 * INCIDENT (juin 2026, suite) : la 1ʳᵉ version de ce filet ré-exécutait `fn()` sur
 * N'IMPORTE QUELLE rejection — y compris quand le verrou AVAIT été obtenu et que c'est
 * l'opération elle-même qui avait échoué (refresh dont la réponse se perd en 2G, mauvais
 * mot de passe…). Conséquence : chaque échec d'auth était rejoué une 2ᵉ fois. Un refresh
 * rejoué réutilise un refresh token déjà consommé côté serveur → Supabase révoque TOUTE
 * la famille de tokens → déconnexion sur tous les onglets/appareils, sessions
 * incohérentes, et localStorage empoisonné jusqu'au vidage manuel. Un login raté rejoué
 * double aussi les tentatives → rate limit → « compte bloqué ».
 * D'où `lockGranted` : le filet « exécuter sans verrou » ne s'applique QUE si le verrou
 * n'a jamais été accordé ; si `fn()` a tourné et a échoué, on propage l'erreur telle quelle.
 */
const LOCK_ACQUIRE_MAX_MS = 5000;

async function deadlockSafeLock<R>(
  name: string,
  acquireTimeout: number,
  fn: () => Promise<R>,
): Promise<R> {
  // Pas de Web Locks (SSR, vieux navigateurs) → exécution directe.
  if (typeof navigator === 'undefined' || !navigator.locks?.request) {
    return await fn();
  }

  const controller = new AbortController();
  const timeoutMs =
    acquireTimeout > 0 ? Math.min(acquireTimeout, LOCK_ACQUIRE_MAX_MS) : LOCK_ACQUIRE_MAX_MS;
  const timer = setTimeout(() => controller.abort(), timeoutMs);

  let lockGranted = false;
  try {
    return await navigator.locks.request(
      name,
      { mode: 'exclusive', signal: controller.signal },
      async () => {
        lockGranted = true;
        clearTimeout(timer);
        return await fn();
      },
    );
  } catch (err) {
    clearTimeout(timer);
    if (lockGranted) {
      // Le verrou a été obtenu : l'erreur vient de fn() (échec d'auth réel).
      // SURTOUT ne pas ré-exécuter — voir l'incident documenté ci-dessus.
      throw err;
    }
    // Verrou non obtenu à temps (probable deadlock d'un contexte figé) ou abandon :
    // filet de sécurité → on exécute sans verrou pour garantir la vivacité de l'auth.
    try {
      console.warn('[Supabase Auth] verrou non obtenu, exécution sans verrou (anti-deadlock):', name, (err as Error)?.name);
    } catch {}
    return await fn();
  }
}

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Connect Supabase in Lovable Cloud.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true,
      lock: deadlockSafeLock,
    }
  });
}

let _supabase: SupabaseClient<Database> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
